BEGIN TRANSACTION;
CREATE TABLE "x_journal_triggers" ("id" integer not null primary key autoincrement, "journal_id" integer not null, "triggers_id" integer not null, foreign key("journal_id") references "journal"("id"), foreign key("triggers_id") references "triggers"("id"));
CREATE TABLE "x_journal_medicine" ("id" integer not null primary key autoincrement, "journal_id" integer not null, "medicines_id" integer not null, "last_taken" datetime null, foreign key("journal_id") references "journal"("id"), foreign key("medicines_id") references "medicines"("id"));
CREATE TABLE "users" ("id" integer not null primary key autoincrement, "name" varchar not null, "email" varchar not null, "password" varchar not null, "first_name" varchar null, "last_name" varchar null, "gender" varchar null, "date_of_birth" date null, "has_diabetes" tinyint null, "has_migraines" tinyint null, "has_glasses" tinyint null, "remember_token" varchar null, "created_at" datetime not null, "updated_at" datetime not null);
CREATE TABLE "triggers" ("id" integer not null primary key autoincrement, "user_id" integer not null, "name" varchar not null, "details" varchar null, "created_at" datetime not null, "updated_at" datetime not null, foreign key("user_id") references "users"("id"));
CREATE TABLE "password_resets" ("email" varchar not null, "token" varchar not null, "created_at" datetime not null);
CREATE TABLE "migrations" ("migration" varchar not null, "batch" integer not null);
INSERT INTO `migrations` VALUES ('2014_10_12_000000_create_users_table',1);
INSERT INTO `migrations` VALUES ('2014_10_12_100000_create_password_resets_table',1);
INSERT INTO `migrations` VALUES ('2015_10_05_034013_create_medicines_table',1);
INSERT INTO `migrations` VALUES ('2015_10_05_034026_create_triggers_table',1);
INSERT INTO `migrations` VALUES ('2015_10_05_034133_create_xtbl_journal_trigger',1);
INSERT INTO `migrations` VALUES ('2015_10_05_034204_create_xtbl_journal_medicine',1);
INSERT INTO `migrations` VALUES ('2015_10_05_040029_create_journal',1);
INSERT INTO `migrations` VALUES ('2015_10_30_034250_journals_update_columns',1);
CREATE TABLE "medicines" ("id" integer not null primary key autoincrement, "user_id" integer not null, "name" varchar not null, "dose" varchar null, "prescribed_by" varchar null, "prescribed_on" date null, "created_at" datetime not null, "updated_at" datetime not null, foreign key("user_id") references "users"("id"));
CREATE TABLE "journals" ("id" integer not null primary key autoincrement, "user_id" integer not null, "location" varchar not null, "severity" integer null, "weather" varchar null, "noise_level" integer null, "light_level" integer null, "created_at" datetime not null, "updated_at" datetime not null, "triggers_id" integer null, "medicines_id" integer null, "name" varchar not null default 'unnamed journal', "description" varchar null, "still_suffering" tinyint null, "start_time" time null, "end_time" time null, "has_aura" tinyint null, "aura_description" varchar null, "has_nausea" tinyint null, "has_vomitted" tinyint null, "has_light_sensativity" tinyint null, "has_sound_sensativity" tinyint null, "has_disrupted" tinyint null, "missed_workshool" tinyint null, "missed_routines" varchar null, "social_plans" varchar null, "activities" varchar null, foreign key("user_id") references "users"("id"));
CREATE UNIQUE INDEX users_name_unique on "users" ("name");
CREATE UNIQUE INDEX users_email_unique on "users" ("email");
CREATE INDEX password_resets_token_index on "password_resets" ("token");
CREATE INDEX password_resets_email_index on "password_resets" ("email");
COMMIT;
